version: 2.1

orbs:
  node: electronjs/node@2.2.0

commands:
  install:
    steps:
#      - run: git config --global core.autocrlf input
      - node/install:
          node-version: '18.18'
      - run: npm i -g electron-builder
      - checkout
      - run: yarn

jobs:
  win-build:
    executor: node/windows
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    steps:
      - add_ssh_keys:
          fingerprints:
            - "XX:XX:XX:XX"
      - install
      - run: yarn package
      - run:
          name: Publish windows build
          shell: powershell.exe
          command: electron-builder -w --publish always
      - store_artifacts:
          path: release
      - persist_to_workspace:
          root: .
          paths:
            - release
  linux-build:
    executor: node/linux
    resource_class: medium
    steps:
      - run: sudo apt-get update
      - install
      - run: sudo apt-get install rpm
      - run: yarn package
      - run: electron-builder -l --publish always
      - store_artifacts:
          path: release
      - persist_to_workspace:
          root: .
          paths:
            - release
workflows:
  build:
    jobs:
      - win-build:
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              only:
                - main
      - linux-build:
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              only:
                - mockup-branch
